server:
  port: 9090

spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

welcome:
  message: Welcome to Green Swap!

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

welcome:
  message: Welcome to Green Swap!
